"""
Agentic RAG Knowledge Base Expert System - LangGraph State Machine

This module defines the core state machine for the RAG system using LangGraph.
The graph orchestrates the retrieval, relevance evaluation, web search fallback,
and answer generation processes through a series of stateful nodes and edges.

Design Philosophy:
- The State serves as the single source of truth across all nodes
- Each node is a pure function that transforms the State
- Edges represent conditional logic for routing between nodes
- The graph supports self-correction loops through feedback mechanisms
"""

from typing import List, Optional, TypedDict, Annotated
from langgraph.graph import StateGraph, END
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI
import operator
from retrieval.hybrid_search import HybridRetriever, RetrievalResult
from retrieval.reranker import get_reranker, BGEReranker
from agents.evaluator import get_evaluator, RelevanceEvaluator
from agents.rewriter import get_rewriter, QueryRewriter
from agents.web_search import get_web_search, WebSearchRetriever
from config.settings import settings
from config.prompts import ANSWER_GENERATION_PROMPT


class RAGState(TypedDict):
    """
    Central state object that flows through all nodes in the LangGraph.
    
    Design Rationale:
    - question: The original user query, immutable throughout the pipeline
    - retrieved_docs: Accumulates documents from vector search and web search
    - relevance_score: Tracks the quality of retrieved documents for self-correction
    - confidence: CRAG evaluation score (0-10) for decision routing
    - final_answer: The synthesized response generated by the LLM
    - retry_count: Prevents infinite loops in query rewriting
    - retrieval_strategy: Records which retrieval method was used (hybrid, web-only, etc.)
    - evaluation_reasoning: Human-readable explanation of confidence score
    """
    question: str
    retrieved_docs: Annotated[List[Document], operator.add]
    relevance_score: float
    confidence: int
    final_answer: str
    retry_count: int
    retrieval_strategy: str
    evaluation_reasoning: str


def retrieval_node(state: RAGState) -> RAGState:
    """
    Node 1: Document Retrieval from Vector Store
    
    Functionality:
    - Performs hybrid search (vector similarity + BM25 keyword matching)
    - Queries Qdrant vector database for relevant documents
    - Applies RRF fusion to combine dense and sparse retrieval results
    - Reranks fused results using BGE-Reranker for higher precision
    - Calculates average relevance score for self-correction decision
    - Updates retrieved_docs, relevance_score, and retrieval_strategy in the State
    
    Design Flow:
    1. Initialize HybridRetriever with Qdrant and embedding model
    2. Perform parallel dense (vector) and sparse (BM25) retrieval
    3. Fuse results using Reciprocal Rank Fusion (RRF)
    4. Rerank top-k candidates using BGE-Reranker cross-encoder
    5. Compute average relevance score across reranked documents
    6. Update State with final results and metadata
    
    Extension Points:
    - Can integrate multiple vector stores for federated search
    - Supports query expansion and reformulation
    - Can add metadata-based filtering (e.g., by date, source)
    - Reranker threshold can be made adaptive based on query complexity
    """
    # Initialize hybrid retriever (lazy initialization on first call)
    # In production, this would be a singleton to avoid re-initialization
    retriever = HybridRetriever(
        top_k=settings.top_k_retrieval,
        vector_weight=settings.vector_search_weight,
        bm25_weight=settings.bm25_search_weight,
    )
    
    # Note: BM25 index must be built before retrieval
    # This would typically be done during the ingestion phase
    # retriever.build_bm25_index(all_documents)
    
    # Perform hybrid retrieval with RRF fusion
    retrieval_result: RetrievalResult = retriever.retrieve(
        query=state["question"],
        use_rrf=True,  # Use RRF for robust score fusion
    )
    
    # Get reranker instance (singleton for efficiency)
    reranker: BGEReranker = get_reranker()
    
    # Rerank retrieved documents using BGE cross-encoder
    # This step significantly improves precision by re-scoring query-doc pairs
    reranked_docs, avg_relevance = reranker.rerank_with_threshold(
        query=state["question"],
        documents=retrieval_result.documents,
        threshold=0.0,  # No filtering at this stage (done in relevance_evaluation_node)
        top_k=settings.top_k_retrieval,
    )
    
    # Extract documents from reranked results
    final_docs = [doc for doc, _ in reranked_docs]
    
    # Update State
    state["retrieved_docs"] = final_docs
    state["relevance_score"] = avg_relevance
    state["retrieval_strategy"] = retrieval_result.strategy
    
    return state


def relevance_evaluation_node(state: RAGState) -> RAGState:
    """
    Node 2: CRAG Relevance Evaluation
    
    CRAG Decision Logic:
    - Confidence >= 7: Direct generation (retrieval is sufficient)
    - 3 <= Confidence < 7: Query rewriting (retrieval is partially relevant)
    - Confidence < 3: Web search fallback (retrieval is insufficient)
    
    Functionality:
    - Evaluates retrieved documents using LLM-based relevance assessment
    - Returns confidence score (0-10) and reasoning
    - Updates State with confidence for conditional routing
    
    Performance Optimization:
    - Uses gpt-4o-mini for 10-20x lower latency than gpt-4
    - Evaluation is a classification task, not generation
    - Small models can reliably judge relevance
    """
    evaluator: RelevanceEvaluator = get_evaluator()
    
    # Evaluate relevance of retrieved documents
    evaluation_result = evaluator.evaluate(
        question=state["question"],
        documents=state["retrieved_docs"],
    )
    
    # Update State with evaluation results
    state["confidence"] = evaluation_result["confidence"]
    state["evaluation_reasoning"] = evaluation_result["reasoning"]
    
    return state


def web_search_node(state: RAGState) -> RAGState:
    """
    Node 3: Web Search Fallback (Triggered when confidence < 3)
    
    Functionality:
    - Activated when retrieval confidence is very low (< 3)
    - Uses Tavily API to fetch real-time web information
    - Merges web search results with existing retrieved_docs
    - Updates retrieval_strategy to indicate web search was used
    
    Design Rationale:
    - Only triggered when local retrieval is completely insufficient
    - Provides fresh information for time-sensitive or niche queries
    - Complements local knowledge base with external sources
    """
    web_search: WebSearchRetriever = get_web_search()
    
    # Perform web search and merge with existing docs
    merged_docs = web_search.search_and_merge(
        query=state["question"],
        existing_docs=state["retrieved_docs"],
    )
    
    # Update State
    state["retrieved_docs"] = merged_docs
    state["retrieval_strategy"] = "web_fallback"
    
    return state


def query_rewrite_node(state: RAGState) -> RAGState:
    """
    Node 3b: Query Rewriting (Triggered when 3 <= confidence < 7)
    
    Functionality:
    - Activated when retrieval confidence is moderate (partially relevant)
    - Generates 3 query variants using LLM
    - Performs parallel retrieval for all variants
    - Selects best result based on reranker scores
    - Increments retry_count to prevent infinite loops
    
    Design Rationale:
    - Moderate confidence suggests documents are relevant but incomplete
    - Query reformulation can capture different semantic angles
    - Parallel retrieval minimizes latency overhead
    - Retry limit prevents runaway loops
    """
    # Check retry limit
    MAX_REWRITES = 2
    if state["retry_count"] >= MAX_REWRITES:
        # Exceeded retry limit, proceed to generation with current docs
        return state
    
    rewriter: QueryRewriter = get_rewriter()
    retriever = HybridRetriever(
        top_k=settings.top_k_retrieval,
        vector_weight=settings.vector_search_weight,
        bm25_weight=settings.bm25_search_weight,
    )
    
    # Retrieve with query variants
    best_docs, best_score, best_query = rewriter.retrieve_with_variants(
        question=state["question"],
        retriever=retriever,
        top_k=settings.top_k_retrieval,
    )
    
    # Update State
    state["retrieved_docs"] = best_docs
    state["relevance_score"] = best_score
    state["retrieval_strategy"] = f"query_rewrite_v{state['retry_count'] + 1}"
    state["retry_count"] += 1
    
    # Re-evaluate after rewriting
    return relevance_evaluation_node(state)


def generation_node(state: RAGState) -> RAGState:
    """
    Node 4: Answer Generation
    
    Functionality:
    - Synthesizes final answer based on retrieved_docs
    - Uses LLM to generate coherent, contextual response
    - Incorporates citations from source documents
    - Updates final_answer in the State
    
    Extension Points:
    - Can implement multi-step reasoning chains
    - Supports different generation strategies (concise, detailed, structured)
    - Can add post-generation validation and fact-checking
    """
    if not state["retrieved_docs"]:
        state["final_answer"] = "抱歉，未找到相关信息来回答您的问题。"
        return state
    
    # Initialize LLM for generation
    llm = ChatOpenAI(
        model=settings.openai_model,
        temperature=0.0,
        api_key=settings.openai_api_key,
    )
    
    # Format documents for the prompt
    docs_text = "\n\n".join([
        f"[来源: {doc.metadata.get('source', 'unknown')} - {doc.metadata.get('url', doc.metadata.get('title', ''))}]\n{doc.page_content}"
        for doc in state["retrieved_docs"]
    ])
    
    # Build the generation prompt
    prompt = ANSWER_GENERATION_PROMPT.format(
        question=state["question"],
        documents=docs_text,
    )
    
    # Generate answer
    response = llm.invoke(prompt)
    state["final_answer"] = response.content
    
    return state


def self_correction_node(state: RAGState) -> RAGState:
    """
    Node 5: Self-Correction Loop (Conditional)
    
    Functionality:
    - Evaluates the quality of generated final_answer
    - Checks for hallucinations, contradictions, or incomplete information
    - If issues detected, increments retry_count and routes back to retrieval
    - Prevents infinite loops via retry_count threshold
    
    Design Philosophy:
    - Enables the system to improve its own outputs
    - Critical for reliability in interview preparation context
    - Balances quality improvement with computational cost
    """
    # TODO: Implement self-evaluation logic
    # TODO: Route back to retrieval if quality is insufficient and retry_count < max_retries
    pass


def route_by_confidence(state: RAGState) -> str:
    """
    Conditional Edge: CRAG routing based on confidence score
    
    CRAG Decision Logic:
    - confidence >= 7: "generate" (direct generation)
    - 3 <= confidence < 7: "query_rewrite" (query rewriting)
    - confidence < 3: "web_search" (web search fallback)
    
    Returns:
        Next node name based on confidence score
    """
    confidence = state.get("confidence", 0)
    
    if confidence >= 7:
        return "generate"
    elif confidence >= 3:
        return "query_rewrite"
    else:
        return "web_search"


def should_retry(state: RAGState) -> str:
    """
    Conditional Edge: Decide whether to retry or finish
    
    Returns:
        "retrieval" if retry_count < max_retries and quality check fails
        "end" if retry_count >= max_retries or quality check passes
    """
    MAX_RETRIES = 2
    # TODO: Add quality check condition
    if state["retry_count"] < MAX_RETRIES:
        return "retrieval"
    return END


def build_graph() -> StateGraph:
    """
    Constructs the complete LangGraph state machine with CRAG decision logic.
    
    Mermaid Flowchart:
    ```mermaid
    graph TD
        Start([开始]) --> Retrieval[检索节点]
        Retrieval --> Evaluation[相关性评估]
        Evaluation -->|置信度 >= 7| Generation[生成节点]
        Evaluation -->|3 <= 置信度 < 7| Rewrite[查询重写]
        Evaluation -->|置信度 < 3| WebSearch[网络搜索]
        Rewrite --> Evaluation
        WebSearch --> Generation
        Generation --> End([结束])
    ```
    
    CRAG Graph Flow:
    1. retrieval_node -> relevance_evaluation_node
    2. relevance_evaluation_node -> [generation | query_rewrite | web_search] (conditional by confidence)
    3. query_rewrite_node -> relevance_evaluation_node (loop for re-evaluation)
    4. web_search_node -> generation_node
    5. generation_node -> END
    
    Returns:
        Compiled StateGraph ready for execution
    """
    workflow = StateGraph(RAGState)
    
    # Add nodes to the graph
    workflow.add_node("retrieval", retrieval_node)
    workflow.add_node("relevance_evaluation", relevance_evaluation_node)
    workflow.add_node("query_rewrite", query_rewrite_node)
    workflow.add_node("web_search", web_search_node)
    workflow.add_node("generation", generation_node)
    
    # Define edges (sequential flow)
    workflow.set_entry_point("retrieval")
    workflow.add_edge("retrieval", "relevance_evaluation")
    
    # Conditional edge: CRAG routing based on confidence
    workflow.add_conditional_edges(
        "relevance_evaluation",
        route_by_confidence,
        {
            "generate": "generation",
            "query_rewrite": "query_rewrite",
            "web_search": "web_search"
        }
    )
    
    # Query rewrite loops back to evaluation
    workflow.add_edge("query_rewrite", "relevance_evaluation")
    
    # Web search proceeds to generation
    workflow.add_edge("web_search", "generation")
    
    # Generation ends the workflow
    workflow.add_edge("generation", END)
    
    return workflow.compile()


if __name__ == "__main__":
    # Example usage for testing the graph structure
    graph = build_graph()
    print("Agentic RAG Graph built successfully!")
    print(f"Graph nodes: {graph.nodes}")
